version: 2

jobs:
  build:
    docker:
    - image: circleci/golang:1.16

    steps:
    - checkout
    - run: go test -v ./...
    - run: go build -tags netgo ./...
    - persist_to_workspace:
        root: .
        paths:
        - hellopod

  push_image:
    docker:
    - image: circleci/golang:1.16

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD quay.io
    - run: docker build -t quay.io/simonpasquier/hellopod:latest .
    - run: docker push quay.io/simonpasquier/hellopod


workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - push_image:
        context: Quay
        requires:
        - build
        filters:
          branches:
            only: master
