version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.16.0

jobs:
  build:
    docker:
      - image: cimg/go:1.19

    steps:
    - checkout
    - prometheus/setup_build_environment:
        docker_version: ""
    - run: go test -v ./...
    - run: go build -tags netgo ./...
    - persist_to_workspace:
        root: .
        paths:
        - hellopod

  push_image:
    docker:
      - image: cimg/go:1.19

    steps:
    - checkout
    - prometheus/setup_build_environment:
        docker_version: ""
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD quay.io
    - run: docker build -t quay.io/simonpasquier/hellopod:latest .
    - run: docker push quay.io/simonpasquier/hellopod

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - push_image:
        context: Quay
        requires:
        - build
        filters:
          branches:
            only: master
